name: Split Bundle

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      CLI_RELEASE: "v2.2.5"
      BUNDLE_RELEASE: "codeql-bundle-20200826"

    strategy:
      matrix: 
        platform: ["linux64", "osx64", "win64"]
        language: ["cpp", "csharp", "go", "java", "javascript", "python"]

    steps:
      - name: Download
        run: |
          wget "https://github.com/github/codeql-cli-binaries/releases/download/${CLI_RELEASE}/codeql-${{matrix.platform}}.zip"
          wget "https://github.com/github/codeql-action/releases/download/${BUNDLE_RELEASE}/codeql-bundle.tar.gz"

